# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\x12\x0f\x64istributed_sim\"6\n\x0bTickRequest\x12\x13\n\x0btick_number\x18\x01 \x01(\x05\x12\x12\n\nlatency_ms\x18\x02 \x01(\x05\"<\n\x0cTickResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1b\n\x13\x63omputation_time_ms\x18\x02 \x01(\x02\"f\n\x0c\x42oundaryData\x12\x13\n\x0btick_number\x18\x01 \x01(\x05\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12.\n\nedge_cells\x18\x03 \x03(\x0e\x32\x1a.distributed_sim.CellState\"B\n\x0b\x42oundaryAck\x12\x19\n\x11\x63onflict_detected\x18\x01 \x01(\x08\x12\x18\n\x10resolved_locally\x18\x02 \x01(\x08**\n\tCellState\x12\t\n\x05\x45MPTY\x10\x00\x12\x08\n\x04TREE\x10\x01\x12\x08\n\x04\x46IRE\x10\x02\x32\xa8\x01\n\nWorkerNode\x12J\n\x0b\x43omputeTick\x12\x1c.distributed_sim.TickRequest\x1a\x1d.distributed_sim.TickResponse\x12N\n\x0fReceiveBoundary\x12\x1d.distributed_sim.BoundaryData\x1a\x1c.distributed_sim.BoundaryAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CELLSTATE']._serialized_start=325
  _globals['_CELLSTATE']._serialized_end=367
  _globals['_TICKREQUEST']._serialized_start=35
  _globals['_TICKREQUEST']._serialized_end=89
  _globals['_TICKRESPONSE']._serialized_start=91
  _globals['_TICKRESPONSE']._serialized_end=151
  _globals['_BOUNDARYDATA']._serialized_start=153
  _globals['_BOUNDARYDATA']._serialized_end=255
  _globals['_BOUNDARYACK']._serialized_start=257
  _globals['_BOUNDARYACK']._serialized_end=323
  _globals['_WORKERNODE']._serialized_start=370
  _globals['_WORKERNODE']._serialized_end=538
# @@protoc_insertion_point(module_scope)
