# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protocol_pb2 as protocol__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerNodeStub(object):
    """The service hosted by each Worker node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeTick = channel.unary_unary(
                '/distributed_sim.WorkerNode/ComputeTick',
                request_serializer=protocol__pb2.TickRequest.SerializeToString,
                response_deserializer=protocol__pb2.TickResponse.FromString,
                _registered_method=True)
        self.ReceiveBoundary = channel.unary_unary(
                '/distributed_sim.WorkerNode/ReceiveBoundary',
                request_serializer=protocol__pb2.BoundaryData.SerializeToString,
                response_deserializer=protocol__pb2.BoundaryAck.FromString,
                _registered_method=True)


class WorkerNodeServicer(object):
    """The service hosted by each Worker node
    """

    def ComputeTick(self, request, context):
        """1. Master tells the worker to compute the next tick
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveBoundary(self, request, context):
        """2. Peer worker sends its boundary data for conflict resolution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeTick': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeTick,
                    request_deserializer=protocol__pb2.TickRequest.FromString,
                    response_serializer=protocol__pb2.TickResponse.SerializeToString,
            ),
            'ReceiveBoundary': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveBoundary,
                    request_deserializer=protocol__pb2.BoundaryData.FromString,
                    response_serializer=protocol__pb2.BoundaryAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_sim.WorkerNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_sim.WorkerNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerNode(object):
    """The service hosted by each Worker node
    """

    @staticmethod
    def ComputeTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_sim.WorkerNode/ComputeTick',
            protocol__pb2.TickRequest.SerializeToString,
            protocol__pb2.TickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveBoundary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_sim.WorkerNode/ReceiveBoundary',
            protocol__pb2.BoundaryData.SerializeToString,
            protocol__pb2.BoundaryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
